title: "Incorporación de Tecnología en Latinoamérica (2000-2025): Da"
description: "Dataset longitudinal (2000-2025) sobre indicadores de adopción de tecnología digital en 21 países de América Latina e Iberia. Variables: penetración d"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/incorporacion-de-tecnologia-en-latinoamerica-2000-2025-dataset-longitudinal"
